version: "3.7"
services:
  jobmanager:
    image: flink:latest
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - /workspaces/apache-flink-training/demo/target:/opt/flink/usrlib
      - /data/movies:/data/movies:cached
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
        state.backend: rocksdb
        state.backend.incremental: true

  taskmanager-1:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - /data/movies:/data/movies:cached
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 5
        taskmanager.memory.process.size: 2048mb
        taskmanager.memory.managed.size: 256mb
        parallelism.default: 1
        state.backend: rocksdb
        state.backend.incremental: true
  taskmanager-2:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - /data/movies:/data/movies:cached
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 5
        taskmanager.memory.process.size: 2048mb
        taskmanager.memory.managed.size: 256mb
        parallelism.default: 1
        state.backend: rocksdb
        state.backend.incremental: true
  sql-client:
      image: flink:latest
      command: bin/sql-client.sh
      depends_on:
        - jobmanager
      environment:
        - |
          FLINK_PROPERTIES=
          jobmanager.rpc.address: jobmanager
          rest.address: jobmanager

  mariadb:
    image: "mariadb:10.10-jammy"
    restart: 'always'
    volumes: 
      - "/var/lib/mysql/data:/mariadb_data"
      - "/var/lib/mysql/logs:/mariadb_log"
      - "/var/docker/mariadb/conf:/etc/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: test_db
      MYSQL_USER: adminr
      MYSQL_PASSWORD: "adminr123"
    ports:
        - "3306:3306"

  rabbitmq:
        image: rabbitmq:3.11.7
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672