version: "3.7"
services:
  jobmanager:
    image: flink:latest
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - /workspaces/apache-flink-training/demo/target:/opt/flink/usrlib
      - /data/movies:/data/movies:cached
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2        

  taskmanager-1:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - /data/movies:/data/movies:cached
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 50
        parallelism.default: 2
  taskmanager-2:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - /data/movies:/data/movies:cached
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 50
        parallelism.default: 2

  sql-client:
      image: flink:latest
      command: bin/sql-client.sh
      depends_on:
        - jobmanager
      environment:
        - |
          FLINK_PROPERTIES=
          jobmanager.rpc.address: jobmanager
          rest.address: jobmanager
  mysql:
      image: mysql:8.0.31
      volumes:
        - mysql-data:/var/lib/mysql
      environment: 
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DATABASE: test_db
      ports:
        - "3306:3306"
volumes:
  mysql-data: